### ISSUE TITLE
Docker and Clusterio Issue

### ISSUE THREAD

**Issue by RADICALAdrift** [clusterio/clusterio#414]
Hi, i'm currently running clusterio via docker via wings on my pterodactyl panel which i run on my dedicated server (installed outside of the docker container on my panel if that helps),
But i'm getting a couple problems problem 1 is with subspace storage https://pastebin.com/Ra11sxrB 
and problem 2 is the servers don't show up in the public server list (i can connect to them via connect to address though) so it isn't a firewall issue

**Comment by psihius** [comment]
Issue number 2 is something to do with how docker sets up the routing and it randomly breaks. 
This is the reason we dropped the idea of supporting Docker on the project level and we do not recommend running it in docker. This is an upstream issue we can't do anything about.

**Comment by Hornwitser** [comment]
This is a configuration issue. [As noted in the README you have to copy the Subspace Storage and Clusterio Lib mods to sharedMods](https://github.com/clusterio/clusterio#setting-up-shared-storage) for it to work. If the servers don't show up in the server list it's likely that you haven't configured a username and token in the instance's factorio settings which is required to publicly list servers.

**Comment by psihius** [comment]
> This is a configuration issue. [As noted in the README you have to copy the Subspace Storage and Clusterio Lib mods to sharedMods](https://github.com/clusterio/clusterio#setting-up-shared-storage) for it to work. If the servers don't show up in the server list it's likely that you haven't configured a username and token in the instance's factorio settings which is required to publicly list servers.

While that does need to be checked (and I misread the initial issue), there is also a docker specific issue when the game connects the game server and game server sees the wrong port. In that case the game is visible in the game browser, but you can't connect to it. We have seen that happen with Gridlock cluster server and the only way to get instance out of that issue is to change the instance port in the docker config and rebuild the container. And since that needs to be done manually, well, when I had to manage over 40 instances, it became a big issue - around 1/3rd of instances on a cluster reboot encountered this problem. As I said previously, the root source is docker itself and hw it sets up Iptables.

**Comment by RADICALAdrift** [comment]
> This is a configuration issue. [As noted in the README you have to copy the Subspace Storage and Clusterio Lib mods to sharedMods](https://github.com/clusterio/clusterio#setting-up-shared-storage) for it to work. If the servers don't show up in the server list it's likely that you haven't configured a username and token in the instance's factorio settings which is required to publicly list servers.

I have configured the username and token options with my own, even going as far as generating the token

> While that does need to be checked (and I misread the initial issue), there is also a docker specific issue when the game connects the game server and game server sees the wrong port. In that case the game is visible in the game browser, but you can't connect to it. We have seen that happen with Gridlock cluster server and the only way to get instance out of that issue is to change the instance port in the docker config and rebuild the container. And since that needs to be done manually, well, when I had to manage over 40 instances, it became a big issue - around 1/3rd of instances on a cluster reboot encountered this problem. As I said previously, the root source is docker itself and hw it sets up Iptables.

So to resolve it i would swap the containers port to 34196 and rebuild

**Comment by Hornwitser** [comment]
> I have configured the username and token options with my own, even going as far as generating the token

You cannot generate a Factorio matchmaking server token yourself, they are issued by Wube. If you have configured it correctly it should show up in the instance log as something like this:

```
   4.482 Info MatchingServer.cpp:114: Matching server game `10764401` has been created.
   4.485 Info ServerMultiplayerManager.cpp:716: Matching server connection resumed
```

**Comment by RADICALAdrift** [comment]
> > I have configured the username and token options with my own, even going as far as generating the token
> 
> You cannot generate a Factorio matchmaking server token yourself, they are issued by Wube. If you have configured it correctly it should show up in the instance log as something like this:
> 
> ```
>    4.482 Info MatchingServer.cpp:114: Matching server game `10764401` has been created.
>    4.485 Info ServerMultiplayerManager.cpp:716: Matching server connection resumed
> ```

Sorry for the confusion i meant re-generate account token via factorio.com as shown here: ![profile](https://user-images.githubusercontent.com/57268573/134821679-30eeceb1-dfba-484a-806e-c1755ff1c0b9.png)

**Comment by psihius** [comment]
@RADICALAdrift I suggest coming to our Discord to the #support channel - easier to share info and you will get faster responses from more people :)

**Comment by RADICALAdrift** [comment]
@psihius I will do in a bit since i'm resolving an issue with something else 👍

**Comment by psihius** [comment]
Closing since the real issue turned out to be something completely different and unrelated to clusterio :)
