### ISSUE TITLE
Use the safe file writing pattern

### ISSUE THREAD

**Issue by Hornwitser** [clusterio/clusterio#416]
The current method for writing data to files in Clusterio is to open the target file for writing (truncating it) and then writing the new data to this file. This is unsafe and can easily lead to complete loss of the content of the target file if the Node.js process crashes or is killed before the data is fully written to the target file. This has happened multiple times, and continues to be a major risk to data stored by Clusterio.

The common pattern for writing new data for a file to disk safely is to write all of the new data to a temporary file and once flushed to disk rename the temporary file into the target file. The replacement via rename is an atomic operation and means the target file is either fully written to disk or not modified at all.

Replace all locations Clusterio truncates and writes directly to a target file with the safe writing pattern. The files of importance includes (but are not limited to) all files in `master.database_directory`, all config files, settings written to instance directories, save patcher, and upload of locale/icon export.

**Comment by jake-87** [comment]
I wrote up a quick replacement for `fs.writeFile`; it should be able to be called in the exact same way, but uses a safe file write pattern: 

```
const fs = require("fs");
const crypto = require("crypto");
const path = require("path");


/*
 * Safely write files. Uses the same syntax as fs.writeFile(),
 * except it uses a rename system to ensure a file is never overwritten without
 * there being a copy of the file on disk.
 */
async function safeWriteFile(...content) {
	
        let userFile = content[0];
	
	if (process.platform === "win32";) {
		let userFileName = path.win.basename(file);
		let dir = path.win.dirname(file);
	}
	else {
		let userFileName = path.posix.basename(file);
		let dir = path.posix.dirname(file);
	}
        let randomString = crypto.randomBytes(16).toString("hex");
	const newFilePath = findUnusedName(userFileName + randomString, dir);
	
        // add some crypto noise to help ensure nothing writes 
        // over what we are trying to write while we are doing it
	
        const newArgs = content.slice(1);
        // gets everything except the file name, so we can replace it
	
        await fs.writeFile(newfilepath, ...newArgs, (err) => {
		if (err) content[content.length - 1](err);
                // error in the write of the temp file, call the users callback func
		
                fs.rename(newfilepath, file, (err) => {
			if (err) {
				fs.unlink(newfilepath, (err) => {
					if (err) throw err;
                                        /* 
                                         * Error in the function itself:
                                         * something went wrong with the rename, so
                                         * we attempt to remove the temp file,
                                         * but it cannot be removed.
                                        */ 
				})
                                content[content.length - 1](err);
                               // error in the rename; call the users callback function
			};
		});
	});
};

// using safeWriteFile:
safeWriteFile("./testOne", "one two three", (err) => {
	console.log(err)
});

// using fs.writeFile:

fs.writeFile("./testTwo", "four five six", (err) => {
	console.log(err)
});
```

By nesting the function inside a callback, we should be able to have this function async, while also ensuring the functions are called in the correct order. Additionally, by calling the user's callback function, we can ensure that we do what the user wants with an error. 

The benefit of this function would be that no other code would really be need to be modified, apart from replacing calls to `fs.writeFile` with calls to `safeWriteFile` and ensuring it all works as expected.

**Comment by Hornwitser** [comment]
😐

This proposed function creates more problems than it solves.

**Comment by jake-87** [comment]
All good then. It was more an idea then anything anyway; generalise a method for safely writing to disk, allowing for less code to be rewritten. Thinking about it with a new perspective, I agree that it’s probably not a great idea.

**Comment by Hornwitser** [comment]
Just to clarify, with the function creating more problems than it solves I mean that the implementation of it is very broken. I will work on solving this issue now, likely with a safeOutputFile function.

**Comment by jake-87** [comment]
Seems reasonable. This implementation is pretty terrible, looking back on it.

**Comment by psihius** [comment]
As far as I understand the double buffer implementations  - usually those are made to be delegated to a separate thread from the main process and handled there and use async I/O. Also, usually some kind of replay log or stuff like that can be used before flushing it big time. We definitely can look up how databases do it since their ACID mechanisms have been around for decades and they definitely know how to do it correctly.

Maybe we should put this into a future improvement - for the moment we kind'a have a bigger fish to fry?  But also I feel this warrants a longer proper investigation and discussion to make it a good implementation. Maybe even do it as a package?

**Comment by jake-87** [comment]
If by "package" you mean something that could be published on NPM and imported into clustorio, someone has already done it: https://www.npmjs.com/package/safe-file-write 

It might be better to simply take inspiration rather then add another dependency, but it seems to do the same thing as described by Hornwitser.

( And what my function was *intended* to do, if I hadn't have written it so badly :p ).
