### ISSUE TITLE
Specify options on installscript programatically

### ISSUE THREAD

**Issue by ElGauchooooo** [clusterio/clusterio#438]
Is there currently a way to specify all the options asked by the installscript programatically by command line?
I've had a small desktop application that lets you manage multiple clusterio instances, which boots up new Amazon AWS EC2 instances as needed and initializes them - without the user having to setting up all clients / master by themself. 

What i'd like to is run something like `npm init @clusterio -admin ElGauchooooo -mode Master -plugins ...` (i guess you get the idea).

**Comment by Danielv123** [comment]
There is no such functionality for the init script afaik, but everything done by the init script can be done through the clusteriomaster/clusterioslave/clusterioctl CLI tools. Only things missing from the CLI is stuff like save uploading (which you can still do by navigating into the correct folder).

Very interested in that application you got, might be something we can learn from it. Cluster management is a big focus for 2.0.

**Comment by Danielv123** [comment]
Here is the install guide from before the init script was added, it will works the same way: https://github.com/clusterio/clusterio/tree/1c4010a744ae0a2c9c56fb61b0a34be83ffca4d5

**Comment by jake-87** [comment]
I don't know about how npm handles init scripts + command line toggles, but `create.js` does seem to have yarg options for the needed parameters, so perhaps that could be adapted at some point?

https://github.com/clusterio/clusterio/blob/master/packages/create/create.js#L498

**Comment by ElGauchooooo** [comment]
> There is no such functionality for the init script afaik, but everything done by the init script can be done through the clusteriomaster/clusterioslave/clusterioctl CLI tools. Only things missing from the CLI is stuff like save uploading (which you can still do by navigating into the correct folder).

I'll give it a try once i get back home, thank you. 

> Very interested in that application you got, might be something we can learn from it. Cluster management is a big focus for 2.0.

Sure thing, for the old clusterio version, it was just a bit hacky, but got the things done to start, persist and re-start all servers, including booting and shutting down all aws instances + backing up in S3 to save money. I'll upload a public version to one of my repos once it reaches a bit more polished state and fits everyone needs. I'll keep you updated.

**Comment by Danielv123** [comment]
create.js is the init script, so if args are supported there then they are supported.On Dec 8, 2021 12:48, ElGauchooooo ***@***.***> wrote:

There is no such functionality for the init script afaik, but everything done by the init script can be done through the clusteriomaster/clusterioslave/clusterioctl CLI tools. Only things missing from the CLI is stuff like save uploading (which you can still do by navigating into the correct folder).

I'll give it a try once i get back home, thank you.

Very interested in that application you got, might be something we can learn from it. Cluster management is a big focus for 2.0.

Sure thing, for the old clusterio version, it was just a bit hacky, but got the things done to start, persist and re-start all servers, including booting and shutting down all aws instances + backing up in S3 to save money. I'll upload a public version to one of my repos once it reaches a bit more polished state and fits everyone needs. I'll keep you updated.

**Comment by Hornwitser** [comment]
Have you tried `--help`? npm init eats the --help if you pass it without -- which isn't even mentioned in `npm init --help`, but whatever.

```
$ npm init @clusterio -- --help
Options:
  --help               Show help                                       [boolean]
  --version            Show version number                             [boolean]
  --log-level          Log level to print to stdout
           [string] [choices: "none", "fatal", "error", "warn", "audit", "info",
                                                    "verbose"] [default: "info"]
  --mode               Operating mode to install
                    [choices: "standalone", "master", "slave", "ctl", "plugins"]
  --admin              Admin account name [standalone/master]           [string]
  --slave-name         Slave name [slave]                               [string]
  --master-url         Master URL [slave/ctl]                           [string]
  --master-token       Master authentication token [slave/ctl]          [string]
  --public-address     DNS/IP Address to connect to this server
                       [standalone/slave]                               [string]
  --factorio-dir       Path to Factorio installation [standalone/slave] [string]
  --plugins            Plugins to install                                [array]
  --download-headless  (Linux only) Automatically download and unpack the latest
                       factorio release. Can be set to false using
                       --no-download-headless.                         [boolean]
```



> There is no such functionality for the init script afaik

Why would you say this without even having looked at the create script?

**Comment by Danielv123** [comment]
> Why would you say this without even having looked at the create script?

Somehow I scrolled right past that section without even looking 🤦‍♂️The dumbest thing is I can even remember using them now.

**Comment by ElGauchooooo** [comment]
Thanks for your reply @Hornwitser , unfortunatelly `npm init @clusterio -- --help` does not work on my end (neither does `npm init @clusterio --help` just in case):

```
ubuntu@ip-xxx-xxx-xxx-xxx:/tmp/clusterio$ npm init @clusterio -- --help
npx: installed 94 in 8.1s
? Operating mode to install (Use arrow keys)
❯ Standalone (install both master and slave on this computer)
  Master only
  Slave only
  Ctl only
  Plugins only
```

I've aswell tried to specify the given arguments you've posted by your help output, yet it still asks for my userinput (like i've just not specified it).

**Comment by ElGauchooooo** [comment]
Thank you @Hornwitser, at least i can now specify anything - except for plugins. I've tried a couple of variants, but it still asks me which plugins i'd like to install.

* `--plugins "Global Chat" --plugins "Inventory Sync"`
* `--plugins ["Global Chat", "Inventory Sync"]`
* `--plugins "Global Chat", "Inventory Sync"`
* `--plugins "Global Chat" "Inventory Sync"`
* `--plugins '["Global Chat","Inventory Sync"]'`

i've tried them all, none worked. Any suggestions?

**Comment by Hornwitser** [comment]
I am not sure how this slipped through, but the installer ignores the --plugins argument. You're supposed to pass npm modules to install as plugin. E.g. `--plugins "@clusterio/plugin-global_chat" "@clusterio/plugin-inventory_sync"`. But since the install ignores it that'll have to be fixed first.

**Comment by Hornwitser** [comment]
It should work now.

**Comment by ElGauchooooo** [comment]
Can confirm, Just tried it. Works like a charm - thank you.
