### ISSUE TITLE
Blank screen getting into the web UI

### ISSUE THREAD

**Issue by gavinunderdown** [clusterio/clusterio#465]
Start up the master, and go to open the web interface, all I get is a blank screen, Inspecting source leads to the following HTML 
`<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="theme-color" content="#2a2a2a" />
		<title>Clusterio</title>
		<script>
				window.webRoot = new URL("./", document.location).pathname;
		</script>
	</head>
	<body>
		<noscript>You need to enable JavaScript to run this app.</noscript>
		<div id="root"></div>
		<script src="[./bundle.js](view-source:http://127.0.0.1:8081/bundle.js)"></script>
	</body>
</html>`

I was not experiencing this issue on Friday July 1, but the game was updated since then. 

I have tried this using Firefox v102.0, _as well as INTERNET EXPLORER_.

I have tried accessing it with 127.0.0.1:8081, localhost:8081, as well as the outward facing network address (10.x or 192.x) 

I ran `npm update` before submitting the issue and it has not been resolved. At this rate I suspect windows firewall might be to blame, even though I have it turned off completely (Windows firewall preventing javascript from hitting the network). 

Any suggestions?

Attached files: config-master, and then the NPM package files. 
[configs.zip](https://github.com/clusterio/clusterio/files/9051171/configs.zip)

**Comment by Hornwitser** [comment]
This is a known problem with disabling loading of plugins (particularly Subspace Storage) from the master config. If you don't want the plugin you can use `npx clusteriomaster plugin remove subpsace_storage` to remove it from plugin-list.json and cause it to not be present at all.

**Comment by gavinunderdown** [comment]
Fixed. Is there a KB or FAQ where this information is posted?

**Comment by Hornwitser** [comment]
It has already been fixed for the next release.
