### ISSUE TITLE
Gather more statistics

### ISSUE THREAD

**Issue by Danielv123** [clusterio/clusterio#49]
- [x] Player list ordered by play time

Get player list using [game.players](http://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.players) then [player.online_time](http://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.online_time)

- [x] Kills and deaths

This information is already tracked by the force, should be easy to extract via luaForce

- [x] Buildings built/destroyed

- [x] Hotpatch merged to master

There is no builtin for this, would need to catch build events and track from that. Will have to wait until we have hotpatch merged into master.

**Comment by justarandomgeek** [comment]
> There is no builtin for this, would need to catch build events and track from that. *Don't think this can be done as a softmod.*

Sure it can, it's just event handlers and a table stuffed into global (or even lazier, just report events as they happen and track them externally)

**Comment by Danielv123** [comment]
Can you add and check the existence of event handlers from the console though? I am not using control.lua yet.

**Comment by kswtch** [comment]
> (or even lazier, just report events as they happen and track them externally)

I would prefer this approach. Data aggregation, manipulation and calculation can be done outside of factorio and therefore not slowing the server instance down. Also it increases the flexibility as to what to do with the data.

**Comment by justarandomgeek** [comment]
>Can you add and check the existence of event handlers from the console though? I am not using control.lua yet.

You can indeed! It's not save/load stable enough for MP, but you can do it for testing or in SP as much as you want. I don't think it'll desync, but i'm sure it's evil in other ways that Rseding can enlighten us about!

(With a little help from a scenario (or mod, but at that point why bother?) you can even ensure that functions stored in a global table get re-registered at the appropriate time, but that's slightly harder)

**Comment by Danielv123** [comment]
Current solution is just to inject the command I want to run whenever I feel like running it. Its still decently short (500 characters) and doesn't seem to cause any weirdness.

**Comment by Danielv123** [comment]
We now gather statistics about who adds and removes items, displayed on graphs on storage page. Click an item to render graphs.

**Comment by psihius** [comment]
Probably should end up as a project in itself

**Comment by Hornwitser** [comment]
Which statistics specifically is this issue about?  There's already production and consumption statistics for items and fluid.

**Comment by psihius** [comment]
We need to do a revision here.
But some stats that can be fun:
* Deaths to trains per player and in total.
* Entities each player built, maybe even per entity type aka detailed statistics. Same can be for removal.
* Per player bug kill stats maybe?
* Train transport statistics maybe? (at least for the train teleport plugin aka "transfered items count with direction where they went".
* Etc. Could ask people on Clusterio and Gridlock what stats they would like.

**Comment by Hornwitser** [comment]
This is not actionable. If there is a specific stat you want implemented you should open an issue describing it or add to [the backlog](https://github.com/orgs/clusterio/projects/2)
