### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by Hornwitser** [clusterio/clusterio#491]
A lot of coding errors result for type errors that could have been caught if TypeScript was used. Having types available would also make code completion work better. It is desirable to migrate the code over to TypeScript.

- [x] Set up a shared JavaScript/TypeScript environment where files can be ported over one at a time
- [x] Port packages/lib
- [x] port pagkages/controller
- [x] port packages/host
- [x] port packages/ctl
- [x] port packages/web_ui
- [x] port plugins/global_chat
- [x] port plugins/inventory_sync
- [x] port plugins/player_auth
- [x] port plugins/research_sync
- [x] port plugins/statistics_exporter
- [x] port plugins/subspace_storage

**Comment by nitin-pandita** [comment]
Hey @Hornwitser  i would like to work on it

**Comment by nitin-pandita** [comment]
> That would be very helpful. Would you mind waiting until I've ported packages/lib to TypeScript and have it merged first? Shouldn't take more than a couple of days at most, and then we can take a package each to port at a time.

sure

**Comment by Hornwitser** [comment]
@nitin-pandita and @Luciole0x I have merged the porting of the lib package now so it should be fairly straight forward to pick a package and start porting it now. See the lib package for how I set up the tsconfig and prepare script step.

**Comment by Luciole0x** [comment]
Ok, I will start working on the controller package.

**Comment by Hornwitser** [comment]
I will work on the ctl package.

**Comment by nitin-pandita** [comment]
I will work on web_ui package

**Comment by Hornwitser** [comment]
There were some problems with the typings I made for the lib package which meant that Link.handle and Link.send/sendTo would result in a type error instead of correctly deducing the types. These should be fixed by #494.

**Comment by Hornwitser** [comment]
I will work on the host package.

**Comment by Luciole0x** [comment]
I will work on the global_chat plugin (all included plugins need the transition to, right ?).
Regarding code coverage, do you have some kind of "philosophy" on how you implement the tests ?
I may try my hand on making some but as I'm still goofing a lot, may prove not too productive... we'll see.

**Comment by Hornwitser** [comment]
If you're not changing the logic of the code you do not need to concern yourself about the coverage. So if the existing tests are doing the same thing after it ports cleanly to TypeScript then that's good enough.

**Comment by Luciole0x** [comment]
I will work on the inventory_sync plugin.

**Comment by Hornwitser** [comment]
@nitin-pandita how is the progress with porting web_ui going?

**Comment by nitin-pandita** [comment]
@Hornwitser I don't see any js file in web_ui, all files are tsx

**Comment by Luciole0x** [comment]
Miss to tell, I did the player_auth, will work on research_sync.
Do you prefer I create a single pull request including all plugins or a pull request per plugin ?
Will wait for #497 to be merge and have a clear idea on what to do on every plugin.

**Comment by Hornwitser** [comment]
You can bunch them up if it makes sense for you. There isn't much code in most of the plugins.

**Comment by nitin-pandita** [comment]
> Are we looking at the same code? There are no .tsx file in this repository. Most of the files in web_ui are .jsx files with no TypeScript typing at all.

Yeah I see it now, there was some error with my vscode

**Comment by Hornwitser** [comment]
@nitin-pandita any progress?

**Comment by Luciole0x** [comment]
@nitin-pandita if you don't have the time to do the transition of the web_ui part do you mind if I try to make it ?

**Comment by Hornwitser** [comment]
Excellent work. Thank you.
