### ISSUE TITLE
Feature Request: Versions in instance list

### ISSUE THREAD

**Issue by n0t49a1n** [clusterio/clusterio#565]
to help with version control and being able to see the cluster as a whole
Would like to see the Version of the instance in the instance tab

below is a mock up of what i need
![image](https://github.com/clusterio/clusterio/assets/87333/9f2c4a48-e9e4-4923-a37a-aab33b04ebe0)

**Comment by n0t49a1n** [comment]
id love to try this but i have no idea how this web works at all

**Comment by CCpersonguy** [comment]
I'll make an attempt at this. The UI change seems straightforward, I'm reading code to figure out which events(s) should be used to send this info to the Controller.

**Comment by Cooldude2606** [comment]
From a quick look, my approach would be expanding `InstanceDetails` to include the factorio version, then within `InstanceInfo::toInstanceDetails` you have access to the instance config where the game version is stored.
