### ISSUE TITLE
Change codecov ci config

### ISSUE THREAD

**Issue by Danielv123** [clusterio/clusterio#588]
Codecov currently gives a big red X in CI if the coverage percentage drops by 0.01%. This is pretty much meaningless noise.

I suggest setting the codecov [treshold](https://docs.codecov.com/docs/commit-status#threshold) at 1% or something to reduce this noise.

I also suggest that if we want it to complain about PRs adding untested non-web interface code we should have it check the coverage for that PR diff specifically, not just the coverage change for the entire project.

It also has some options for not commenting when there is no coverage change etc, which would be nice.

**Comment by Hornwitser** [comment]
Set it to informational maybe? I never really looked at the checkmark or red x that codecov gives on pull requests.
