### ISSUE TITLE
Add clean script

### ISSUE THREAD

**Issue by Hornwitser** [clusterio/clusterio#589]
It would be useful to have a `clean` script which deletes the `{packages,plugins}/*/dist` folders and can be used before publishing to make sure no leftover files from previous builds are accidentally included into the published packages.

This script should ideally work on both Windows and Linux, and be documented as part of the publishing procedure in docs/contributing.md.

**Comment by Danielv123** [comment]
How about making a CI task for publishing instead? That reduces the chance of human error significantly.
