### ISSUE TITLE
Overflow of server_select gui

### ISSUE THREAD

**Issue by n0t49a1n** [clusterio/clusterio#597]
server switch cannot access last colum/2 colums of servers when over 100 choices
all the server select title also scrolls off aswell
issue
![image](https://github.com/clusterio/clusterio/assets/87333/7e2b7e8a-af1b-4773-bd5b-cc544e69a367)

wider image due to UWQHD
![image](https://github.com/clusterio/clusterio/assets/87333/664b94e1-3d00-4c99-a59c-5378c10a1c22)

**Comment by Danielv123** [comment]
Ah, it finally happenedOn 18 Feb 2024 11:25, Ash ***@***.***> wrote:
server switch cannot access last colum/2 colums of servers when over 100 choices
issue
image.png (view on web)
wider image due to UWQHD
image.png (view on web)

**Comment by ILLISIS** [comment]
Keen for this!

**Comment by commanderguy3001** [comment]
if we get a solution to this problem: it would be neat to also get the option to sort/group servers together, and collapse groups to not take up as much space. specific example in this case: be able to group all copper smelting servers together, and collapse them into a single entry "copper-smelters" that you can open up if need be. same for iron smelters, green circuits, etc.

**Comment by Danielv123** [comment]
I know the antd table component we use has an option for collapsible/tree style views already including drag and drop - might be a good idea to make it organize the same way as server select.

Being able to group servers and then start/stop entire groups might also be handy.

**Comment by commanderguy3001** [comment]
I was only really envisioning it ingame, but I guess expanding that to the master as well might be useful, yeah...

**Comment by Danielv123** [comment]
I implemented a far simpler solution, mostly because it was less work and I got annoyed with having too many instances in the GUI for my own cluster. It has a single column of instances with a scrollbar instead of the multi column layout and a search bar for finding stuff when it becomes a bit too much to look through.

I think this is sufficient to close this issue once merged.
