### ISSUE TITLE
Unexpected error when opening mod packs

### ISSUE THREAD

**Issue by mukkie** [clusterio/clusterio#609]
When opening some of my mod packs, I get an unexpected error

List of mod packs
![mod_pack-01](https://github.com/clusterio/clusterio/assets/24451004/5a5019b9-dde9-449b-933e-8288495d5a19)

Success opening "Warptorio"
![mod_pack-02](https://github.com/clusterio/clusterio/assets/24451004/dfe83c60-68d5-40ac-a7d3-e789b6b2ee4c)

Fail opening "Crash Site" or "Diggy". Note both of these are scenarios
![mod_pack-03](https://github.com/clusterio/clusterio/assets/24451004/b255bad4-b16b-47c8-bd26-06de4a2eb2ed)

**Comment by Hornwitser** [comment]
Can you provide the database/mod-packs.json file from the controller and/or open the web console to see if there's more info about the error thrown?

**Comment by mukkie** [comment]
![web-console-host](https://github.com/clusterio/clusterio/assets/24451004/28de8c2f-ebee-4cc4-8fae-11a756d286b0)
nothing appears in the logs

[mod-packs.json](https://github.com/clusterio/clusterio/files/14753832/mod-packs.json)

**Comment by Hornwitser** [comment]
I'm not able to reproduce this. Which version of Clusterio are you running? And can you open the developer tools (right click on the page a and select inspect elements) and see if there are any error messages in the console there?

**Comment by mukkie** [comment]
2.0.0-alpha.17

No error messages in the console :-(

**Comment by Hornwitser** [comment]
> No error messages in the console :-(

That does not compute. When an error is thrown like you showed it gets printed to the developer tools console. See image below.

![image](https://github.com/clusterio/clusterio/assets/14362102/62d4de87-4ef2-4357-b6be-5d49c0f6a7f6)

**Comment by Hornwitser** [comment]
I suspect this is due to the exported contents of static/settings.<hex-string>.json file associated with the mod pack that gets created when running export data on an instance.

**Comment by Hornwitser** [comment]
Do you have any way to reproduce this?

**Comment by mukkie** [comment]
I can reproduce it all the time. Every time I click on the mod pack, I get the error. I don't know how I can reproduce it for you though. 
Is there a way I can delete the mod pack? I can't open it to delete it from within the mod pack itself.

**Comment by mukkie** [comment]
I've noted that the only two mod-packs affected were for different RedMew scenarios. The scenarios are selected by changing a config file in the Scenario directory. Could that have anything to do with it?

**Comment by Hornwitser** [comment]
> Could that have anything to do with it?

No, this is caused by a missing colour setting in the mod pack. You can fix it by assigning the mod pack to an instance and then running a data export via the "More > Export data" button on the instance.
