### ISSUE TITLE
Unable to restart instance after a patched in file is deleted

### ISSUE THREAD

**Issue by Danielv123** [clusterio/clusterio#611]
I updated factorio from 1.1.104 to 1.1.107 using the ingame updater. After updating, I get the following error both on the host and in the web interface developer tools when attempting to restart the running instance to apply the update:

[error] TypeError: Cannot read properties of null (reading 'async')
    at /Users/danielv/project_files/clusterio/packages/host/dist/node/src/patch.js:98:100
    at Array.map (<anonymous>)
    at SaveModule.fromSave (/Users/danielv/project_files/clusterio/packages/host/dist/node/src/patch.js:98:61)
    at /Users/danielv/project_files/clusterio/packages/host/dist/node/src/patch.js:182:135
    at Array.map (<anonymous>)
    at PatchInfo.fromSave (/Users/danielv/project_files/clusterio/packages/host/dist/node/src/patch.js:182:115)
    at patch (/Users/danielv/project_files/clusterio/packages/host/dist/node/src/patch.js:330:37)
    at async Instance.prepareSave (/Users/danielv/project_files/clusterio/packages/host/dist/node/src/Instance.js:661:9)
    at async Instance.handleInstanceStartRequest (/Users/danielv/project_files/clusterio/packages/host/dist/node/src/Instance.js:823:24)

The issue remains after restarting the host and controller, however does not apply to newly created instances.

**Comment by Hornwitser** [comment]
In a patched save the `clusterio.json` file contains a list of all modules put into the save, and each modules have a `"files"` array with every file that was written into the save for that module. Error is thrown at https://github.com/clusterio/clusterio/blob/79c1a2dc99da6eac79f54b3d55715d9e4f354c15/packages/host/src/patch.ts#L81 and indicates a file that was written into the save no longer exists. I guess Factorio didn't like the file and deleted it.

**Comment by Danielv123** [comment]
Well thats interesting. Let me investigate what file it deleted

**Comment by Danielv123** [comment]
Hm, looks like it got rid of the .gitignore in my module folder. Interesting. Guess I won't put it in there.

**Comment by Hornwitser** [comment]
The error condition of a file being missing should be handled gracefully instead of giving a cryptic error.

**Comment by Danielv123** [comment]
What would be the graceful way of handling this? Logging the missing file? Re-patching the save to include all the files?

**Comment by Hornwitser** [comment]
Log a warning that the file went missing. The current patch logic already replaces all patched in files with files from the modules to patch in.
