### ISSUE TITLE
How to use a modded mod-setting.dat file in a server

### ISSUE THREAD

**Issue by YR1044** [clusterio/clusterio#617]
This repo's readme  says` For managing the mod settings, the mod-settings.dat and mod-list.json files will also be linked/copied over if present in sharedMods, but since Factorio creates these files automatically it might be necessary to delete them from each instance's mods folder for changes to them in sharedMods to take effect.`

but there is no  `sharedMods` folder in my case, and I tried to put my mod-setting.dat in my instance's `mods` folder, but it was overwrited as soon as I start my server up.

How to deal with it? Thanks a lot

**Comment by YR1044** [comment]
I am running in a windows 10 pc with standalone mode

**Comment by Hornwitser** [comment]
Sorry about that, the README is currently out of date.

The current way manage mods and change mod settings is as follows:
1. Under the "Mods" on the controller's web interface upload the mods you wish to use. Alternatively you can copy them to the "mods" folder on the controller and restart the controller.
2. Create a mod pack and add the mods you wish to use to the mod pack.
3. Assign the mod pack to an instance and run an export data action. This option is available under the "More" button when the instance is stopped.
4. The mod settings should now be available to edit in the Mod Pack.

If you already set everything up in single player and don't want to set it up again you could use the command in the [Migrating from alpha 13](https://github.com/clusterio/clusterio/blob/master/docs/migrating-from-2.0.0-alpha.13.md#before-updating) document to create a mod pack string for your configuration and then import that as step 2. Note that there's currently an issue with mods that have leading zeros in the version number when doing that, so if you if you have a mod with a leading zero in the version you will need to remove it from the mod pack and the add it back again for it to work.
