### ISSUE TITLE
Implement serialization of factorio 2.0 crafting queue

### ISSUE THREAD

**Issue by Cooldude2606** [clusterio/clusterio#690]
Introduced by #686 in [inventroy_sync/serialize.lua](https://github.com/clusterio/clusterio/blob/05ca4eb25edfc12ebca6479620bcb3cad1572dee/plugins/inventory_sync/module/serialize.lua#L309)

To get all first party plugins into a bare minimum working state for factorio 2.0 the serialization of the crafting queue was not implemented. This should be implemented using the new api while maintaining backwards compatibilty with the `v2_storage_api` / `v2_crafting_queue` flag.

**Comment by Danielv123** [comment]
Is it sufficient to support 1.1 -> 2.0 migration of inventories, or should bidirectional migrations be supported?

**Comment by Danielv123** [comment]
No matter, I forgot handcrafting with quality isn't a thing. Its fully back and forth compatible.

**Comment by Cooldude2606** [comment]
While in this case it was trival to impliment bidirectional migration, I do not believe this should be a target for all cases. This is because there is the possibilty of additions / removals which can not be migrated without the loss of data.
